name: ReBuild APK

on:
  workflow_dispatch:
   inputs:
      URL:
        description: 'Download URL'
        required: true
        default: ''
      NAME:
        description: 'Name of App'
        required: true
        default: ''

env:              
  URL: ${{ github.event.inputs.URL }}
  NAME: ${{ github.event.inputs.NAME }}.apk
  OUT: ${{ github.event.inputs.NAME }}-signed.apk
  DIR: ${{ github.event.inputs.NAME }}
  TZ: Asia/Kolkata
jobs:
  ApkTool:
    runs-on: ubuntu-latest

    steps:
       - name: Checkout
         uses: actions/checkout@master
           
       - name: Initializing environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk aria2 apksigner zipalign
                
       - name: Apktool
         run: |
            aria2c $URL; aria2c ${{ secrets.KEY }} 
            aria2c https://bitbucket.org/iBotPeaches/apktool/downloads/apktool_2.9.3.jar ; ls
            java -jar apktool_2.9.3.jar d *.apk -o $DIR ; rm *.apk; ls
       
       - name: Build
         run: |
              cd $DIR ; ls ; cd lib; rm -rf *x86* *v7a*; echo "Redundant libs deleted"; ls 
              cd ../..
              java -jar apktool_2.9.3.jar b $DIR $NAME; mv $DIR/dist/*.apk ./$NAME
              apksigner sign --ks pkcs-keystore.jks --out $OUT --ks-key-alias ${{ secrets.ALIAS }} --ks-pass pass:${{ secrets.PASS }} --key-pass pass:${{ secrets.PASS }} $NAME              
       - name: Upload apk
         uses: actions/upload-artifact@v4
         with:
          name: ${{ env.OUT }}
          path: ${{ env.OUT }}
